spring:
  application:
    name: StudentServiceTesting

  datasource:
    url: "jdbc:sqlserver://TNS-IT-DESKTOP\\SQLEXPRESS;databaseName=student_test_db;integratedSecurity=true;encrypt=true;trustServerCertificate=true;"
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

server:
  port: 8080